// src/content/packPadrao.js
// Pacote de cartas "padrão", usado pelos modos Básico e Caótico.
//
// Estrutura de uma carta:
//   { id, rarity: 'comum'|'especial'|'caos'|'lendaria', text, category, effect }
//
// `effect` é opcional (a maioria das cartas comuns/especiais não tem).
// Quando existe, `type` aponta para um handler em src/cardEffects.js.
// Para adicionar uma carta nova, basta empurrar mais um objeto neste
// array — nenhuma outra parte do código precisa mudar.

const PACK_PADRAO = [
  // ============================================================
  // COMUM
  // ============================================================
  { id: 'p-c-01', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente peidaria no elevador e ia fingir que não foi ele?' },
  { id: 'p-c-02', rarity: 'comum', category: 'sobrevivencia', text: 'Se o mundo estivesse acabando agora, quem seria o primeiro a querer ir cagar?' },
  { id: 'p-c-03', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente ia comer escondido a última fatia sabendo que outra pessoa queria?' },
  { id: 'p-c-04', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente daria uma "sugestão sincera" que ninguém pediu e ia magoar todo mundo?' },
  { id: 'p-c-05', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente peidaria durante um momento romântico e ia negar até debaixo de tortura?' },
  { id: 'p-c-06', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia fingir que não viu a mensagem só pra não ter que responder?' },
  { id: 'p-c-07', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente cairia feio na frente de todo mundo e ia levantar rindo pra disfarçar?' },
  { id: 'p-c-08', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente comeria algo caído no chão e não ia contar pra ninguém?' },
  { id: 'p-c-09', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente pegaria emprestado e "esqueceria" de devolver de propósito?' },
  { id: 'p-c-10', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia dar close no espelho achando que ninguém tá vendo?' },
  { id: 'p-c-11', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente soltaria um "eu não ligo" mas no fundo tá morrendo de ciúmes?' },
  { id: 'p-c-12', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente ia brigar com o próprio celular quando a internet cai?' },
  { id: 'p-c-13', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente fingiria estar sem sinal pra não atender uma ligação chata?' },
  { id: 'p-c-14', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia deixar o cheiro de comida no micro-ondas do trabalho de propósito?' },
  { id: 'p-c-15', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia arrotar bem alto na frente de gente que acabou de conhecer?' },
  { id: 'p-c-16', rarity: 'comum', category: 'decisoes-ruins', text: 'Quem provavelmente inventaria uma doença pra sair mais cedo do trabalho?' },
  { id: 'p-c-17', rarity: 'comum', category: 'competicao', text: 'Quem provavelmente entraria numa fila errada só por teimosia e não ia admitir o erro?' },
  { id: 'p-c-18', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia fuçar a geladeira da casa dos outros sem pedir?' },
  { id: 'p-c-19', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia chorar assistindo um comercial de margarina?' },
  { id: 'p-c-20', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ia dar um jeitinho de não pagar a rodada e ninguém ia perceber na hora?' },
  { id: 'p-c-21', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia demorar 40 minutos no banho e culpar o aquecedor?' },
  { id: 'p-c-22', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia soltar um pum silencioso e fugir da cena do crime?' },
  { id: 'p-c-23', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente ia mentir sobre ter lido o grupo só pra não ter trabalho de responder?' },
  { id: 'p-c-24', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia se afogar em autoconfiança no karaokê e cantar horrivelmente feliz?' },
  { id: 'p-c-25', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia fingir gostar de um presente horrível na cara de quem deu?' },
  { id: 'p-c-26', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente esqueceria a própria senha do banco pela quinta vez esse mês?' },
  { id: 'p-c-27', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia dormir no ônibus e passar do ponto todo santo dia?' },
  { id: 'p-c-28', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia fingir que tá calmo enquanto surta por dentro?' },
  { id: 'p-c-29', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia dar risada na hora errada num momento sério?' },
  { id: 'p-c-30', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia narrar em voz alta o próprio pum como se fosse notícia?' },
  { id: 'p-c-31', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente ia stalkear o ex e curtir uma foto de 2018 sem querer?' },
  { id: 'p-c-32', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia brigar feio no trânsito e depois fingir santo em outro contexto?' },
  { id: 'p-c-33', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente ia comer o lanche de outra pessoa na geladeira do trabalho?' },
  { id: 'p-c-34', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ia inventar uma desculpa esfarrapada pra não pagar o Uber?' },
  { id: 'p-c-35', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia rir mais alto que todo mundo da própria piada?' },
  { id: 'p-c-36', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia levar o cachorro pra passear só pra fugir de uma conversa chata?' },
  { id: 'p-c-37', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia soltar um "não tô bravo" berrando igual bravo?' },
  { id: 'p-c-38', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente ia sumir bem na hora de ajudar a lavar a louça?' },
  { id: 'p-c-39', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente daria um close impecável na foto e um caos completo na vida real?' },
  { id: 'p-c-40', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia fingir que entendeu a piada só pra não parecer por fora?' },
  { id: 'p-c-41', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia peidar durante um treino de academia e culpar o barulho do aparelho?' },
  { id: 'p-c-42', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente esqueceria o próprio aniversário de casamento?' },
  { id: 'p-c-43', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ia comprar roupa nova só pra postar e nunca mais usar?' },
  { id: 'p-c-44', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente ia dar match e sumir sem nunca conversar?' },
  { id: 'p-c-45', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia se perder num estacionamento e demorar 20 minutos pra achar o carro?' },
  { id: 'p-c-46', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia soltar uma piada tão ruim que todo mundo ia rir de vergonha alheia?' },
  { id: 'p-c-47', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia inventar que "tá quase chegando" ainda de pijama?' },
  { id: 'p-c-48', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente ia deixar o grupo no visto por três dias e agir como se nada tivesse acontecido?' },
  { id: 'p-c-49', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia roncar tão alto que assustaria os vizinhos?' },
  { id: 'p-c-50', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia chorar de rir até fazer xixi um pouquinho e nunca admitir?' },
  { id: 'p-c-51', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente ia fingir estar filmando um vídeo importante só pra tirar selfie escondido?' },
  { id: 'p-c-52', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ia gastar o último dinheiro do mês achando que "ainda falta muito" pro salário?' },
  { id: 'p-c-53', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia dar uma de médico no grupo achando que sabe curar tudo com chá?' },
  { id: 'p-c-54', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia tropeçar em nada e olhar pro chão como se fosse culpa dele?' },
  { id: 'p-c-55', rarity: 'comum', category: 'competicao', text: 'Quem provavelmente ia comer pimenta pra parecer durão e sofrer calado depois?' },
  { id: 'p-c-56', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia dizer "já tô indo" enquanto ainda nem tomou banho?' },
  { id: 'p-c-57', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia soltar o pior cheiro de pé do grupo e jurar de pés juntos que não é ele?' },
  { id: 'p-c-58', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente ia postar indireta e depois falar "não é sobre você" quando é 100% sobre a pessoa?' },
  { id: 'p-c-59', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia esquecer o nome de alguém que já apresentaram tipo 5 vezes?' },
  { id: 'p-c-60', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia dar risada nervosa no meio de um assunto sério e piorar tudo?' },
  { id: 'p-c-61', rarity: 'comum', category: 'decisoes-ruins', text: 'Quem provavelmente ia fingir que caiu a ligação só pra não continuar uma discussão?' },
  { id: 'p-c-62', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia dar uma de expert em vinho sem saber diferenciar tinto de suco de uva?' },
  { id: 'p-c-63', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia soltar um grito assustador só de ver uma barata do outro lado da sala?' },
  { id: 'p-c-64', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia usar a mesma roupa dois dias seguidos e jurar que é diferente?' },
  { id: 'p-c-65', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia dar uma de "eu avisei" antes mesmo de saber se deu errado mesmo?' },
  { id: 'p-c-66', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente ia se cortar fazendo comida e continuar cozinhando pra não perder a receita?' },
  { id: 'p-c-67', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente ia gritar "eu não tô gritando" no volume mais alto possível?' },
  { id: 'p-c-68', rarity: 'comum', category: 'vergonha', text: 'Quem provavelmente ia peidar dormindo e acordar assustado com o próprio barulho?' },
  { id: 'p-c-69', rarity: 'comum', category: 'decisoes-ruins', text: 'Quem provavelmente ia inventar uma reunião falsa só pra sair mais cedo de outro compromisso chato?' },
  { id: 'p-c-70', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia comer escondido no quarto e deixar o pacote vazio debaixo da cama por semanas?' },
  { id: 'p-c-71', rarity: 'comum', category: 'escola', text: 'Quem provavelmente colava na prova e ainda tirava nota menor que quem ele copiou?' },
  { id: 'p-c-72', rarity: 'comum', category: 'escola', text: 'Quem provavelmente inventava que "o cachorro comeu o caderno" até depois de adulto?' },
  { id: 'p-c-73', rarity: 'comum', category: 'escola', text: 'Quem provavelmente dormiria numa aula chata e acordaria babando na própria mão?' },
  { id: 'p-c-74', rarity: 'comum', category: 'escola', text: 'Quem provavelmente faria o trabalho em grupo inteiro sozinho e não reclamaria até estourar?' },
  { id: 'p-c-75', rarity: 'comum', category: 'escola', text: 'Quem provavelmente levaria bronca e ainda ia rir no meio da bronca?' },
  { id: 'p-c-76', rarity: 'comum', category: 'escola', text: 'Quem provavelmente chutaria a resposta certa numa prova de múltipla escolha e ficaria se achando o gênio?' },
  { id: 'p-c-77', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente pediria dinheiro emprestado e "esqueceria" o valor exato de propósito?' },
  { id: 'p-c-78', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente investiria numa ideia maluca de amigo só pra não ficar de fora?' },
  { id: 'p-c-79', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente compraria algo caro parcelado sem calcular se cabe no orçamento?' },
  { id: 'p-c-80', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ia negociar até o último centavo numa compra de R$5?' },
  { id: 'p-c-81', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente ganharia na loteria e gastaria tudo em um mês?' },
  { id: 'p-c-82', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente teria 47 abas abertas no celular e nunca fecharia nenhuma?' },
  { id: 'p-c-83', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente responderia um áudio de 8 minutos pra uma pergunta de "sim ou não"?' },
  { id: 'p-c-84', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente perderia a senha do wi-fi da própria casa?' },
  { id: 'p-c-85', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente postaria uma foto e ficaria checando as curtidas a cada 2 minutos?' },
  { id: 'p-c-86', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente mandaria mensagem no grupo errado sobre outra pessoa do grupo?' },
  { id: 'p-c-87', rarity: 'comum', category: 'jogos', text: 'Quem provavelmente xingaria o controle de videogame achando que a culpa é dele e não do jogador?' },
  { id: 'p-c-88', rarity: 'comum', category: 'jogos', text: 'Quem provavelmente trapacearia num jogo de tabuleiro em família e ia negar até o fim?' },
  { id: 'p-c-89', rarity: 'comum', category: 'jogos', text: 'Quem provavelmente levaria um jogo de criança tão a sério que ia acabar brigando?' },
  { id: 'p-c-90', rarity: 'comum', category: 'jogos', text: 'Quem provavelmente comemoraria uma vitória boba como se tivesse ganhado a Copa do Mundo?' },
  { id: 'p-c-91', rarity: 'comum', category: 'criatividade', text: 'Quem provavelmente inventaria uma desculpa tão criativa que quase merece um prêmio?' },
  { id: 'p-c-92', rarity: 'comum', category: 'criatividade', text: 'Quem provavelmente criaria uma teoria da conspiração sobre algo completamente bobo?' },
  { id: 'p-c-93', rarity: 'comum', category: 'criatividade', text: 'Quem provavelmente inventaria um apelido ruim pra alguém e faria ele pegar de vez?' },
  { id: 'p-c-94', rarity: 'comum', category: 'sobrevivencia', text: 'Quem provavelmente entraria em pânico primeiro se a luz acabasse durante uma tempestade?' },
  { id: 'p-c-95', rarity: 'comum', category: 'sobrevivencia', text: 'Quem provavelmente comeria a comida estragada só pra não desperdiçar?' },
  { id: 'p-c-96', rarity: 'comum', category: 'sobrevivencia', text: 'Quem provavelmente ia sobreviver mais tempo perdido numa trilha sem GPS?' },
  { id: 'p-c-97', rarity: 'comum', category: 'competicao', text: 'Quem provavelmente ficaria puto de perder até num jogo que nem gosta de jogar?' },
  { id: 'p-c-98', rarity: 'comum', category: 'competicao', text: 'Quem provavelmente inventaria uma regra nova no meio do jogo só porque tá perdendo?' },
  { id: 'p-c-99', rarity: 'comum', category: 'decisoes-ruins', text: 'Quem provavelmente mandaria aquela mensagem que devia ter apagado antes de enviar?' },
  { id: 'p-c-100', rarity: 'comum', category: 'decisoes-ruins', text: 'Quem provavelmente tomaria uma decisão importante da vida baseado num sinal aleatório?' },
  { id: 'p-c-101', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente ia se perder tentando seguir o próprio GPS?' },
  { id: 'p-c-102', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente contaria seu segredo achando que "não tinha nada demais"?' },
  { id: 'p-c-103', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente daria uma de forte e ia chorar escondido no banheiro logo depois?' },
  { id: 'p-c-104', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia dar risada alta num velório sem querer e nunca mais superar a vergonha?' },
  { id: 'p-c-105', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente confundiria o sal com açúcar e serviria assim mesmo?' },
  { id: 'p-c-106', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente sairia de casa com a roupa do avesso e só ia perceber depois de horas?' },
  { id: 'p-c-107', rarity: 'comum', category: 'jogos', text: 'Quem provavelmente ia dar um pulo de susto num jogo de terror e derramar a bebida em todo mundo?' },
  { id: 'p-c-108', rarity: 'comum', category: 'escola', text: 'Quem provavelmente esqueceria completamente que tinha prova hoje?' },
  { id: 'p-c-109', rarity: 'comum', category: 'dinheiro', text: 'Quem provavelmente compraria comida por impulso só de olhar pro anúncio na tela?' },
  { id: 'p-c-110', rarity: 'comum', category: 'sobrevivencia', text: 'Quem provavelmente seria o mais tranquilo se o carro quebrasse no meio do nada?' },
  { id: 'p-c-111', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente diria "tô de boa" com uma cara nada de boa?' },
  { id: 'p-c-112', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente ia falar um nome errado bem na hora de apresentar alguém importante?' },
  { id: 'p-c-113', rarity: 'comum', category: 'tecnologia', text: 'Quem provavelmente compraria um gadget caríssimo e usaria só uma vez?' },
  { id: 'p-c-114', rarity: 'comum', category: 'amizade', text: 'Quem provavelmente marcaria de sair e cancelaria em cima da hora com a pior desculpa?' },
  { id: 'p-c-115', rarity: 'comum', category: 'competicao', text: 'Quem provavelmente treinaria escondido só pra surpreender todo mundo numa competição boba?' },
  { id: 'p-c-116', rarity: 'comum', category: 'situacoes-absurdas', text: 'Quem provavelmente escorregaria numa casca de banana de verdade pelo menos uma vez na vida?' },
  { id: 'p-c-117', rarity: 'comum', category: 'criatividade', text: 'Quem provavelmente inventaria uma história completamente mentirosa e conseguiria fazer todo mundo acreditar?' },
  { id: 'p-c-118', rarity: 'comum', category: 'cotidiano', text: 'Quem provavelmente colocaria o despertador e desligaria dormindo sem nem lembrar?' },
  { id: 'p-c-119', rarity: 'comum', category: 'personalidade', text: 'Quem provavelmente faria um drama gigante por uma coisa pequena e depois esqueceria em cinco minutos?' },
  { id: 'p-c-120', rarity: 'comum', category: 'situacoes-sociais', text: 'Quem provavelmente daria oi pra alguém achando que conhecia e não conhecia nada?' },

  // ============================================================
  // ESPECIAL (pergunta mais provocativa; efeito raro, mas possível)
  // ============================================================
  { id: 'p-e-01', rarity: 'especial', category: 'decisoes-ruins', text: 'Quem provavelmente faria uma cagada por dinheiro?' },
  { id: 'p-e-02', rarity: 'especial', category: 'competicao', text: 'Quem provavelmente venderia um amigo pra ganhar num programa de televisão?' },
  { id: 'p-e-03', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente entraria numa treta feia do grupo só por pura teimosia?' },
  { id: 'p-e-04', rarity: 'especial', category: 'vergonha', text: 'Quem provavelmente culparia o cachorro por um pum que foi dele mesmo?' },
  { id: 'p-e-05', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente sumiria do grupo por uma semana sem dar satisfação a ninguém?' },
  { id: 'p-e-06', rarity: 'especial', category: 'situacoes-sociais', text: 'Quem provavelmente terminaria um relacionamento sério por mensagem de texto com bom dia junto?' },
  { id: 'p-e-07', rarity: 'especial', category: 'personalidade', text: 'Quem provavelmente culparia todo mundo antes de admitir que errou feio?' },
  { id: 'p-e-08', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente fingiria estar ocupadíssimo pra fugir de ajudar numa mudança de casa?' },
  { id: 'p-e-09', rarity: 'especial', category: 'situacoes-absurdas', text: 'Quem provavelmente juraria "não bebi tanto assim" segurando na parede pra não cair?' },
  { id: 'p-e-10', rarity: 'especial', category: 'tecnologia', text: 'Quem provavelmente revira seu celular no primeiro segundo que você desgruda dele?' },
  { id: 'p-e-11', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente contaria um segredo seu achando que "não tinha nada demais"?' },
  { id: 'p-e-12', rarity: 'especial', category: 'personalidade', text: 'Quem provavelmente choraria pra conseguir o que quer e sabe exatamente que funciona?' },
  { id: 'p-e-13', rarity: 'especial', category: 'situacoes-sociais', text: 'Quem provavelmente daria em cima do crush de outra pessoa do grupo e falaria "eu não sabia"?' },
  { id: 'p-e-14', rarity: 'especial', category: 'personalidade', text: 'Quem provavelmente mentiria na cara dura olhando bem nos seus olhos?' },
  { id: 'p-e-15', rarity: 'especial', category: 'competicao', text: 'Quem provavelmente puxaria o tapete de um amigo pra ganhar uma vantagem besta?' },
  { id: 'p-e-16', rarity: 'especial', category: 'dinheiro', text: 'Quem provavelmente fingiria uma crise pra não pagar a própria parte da conta?' },
  { id: 'p-e-17', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente falaria mal de alguém e depois seria super simpático na cara da pessoa?' },
  { id: 'p-e-18', rarity: 'especial', category: 'personalidade', text: 'Quem provavelmente trairia a própria palavra por uma vantagem pequena?' },
  { id: 'p-e-19', rarity: 'especial', category: 'competicao', text: 'Quem provavelmente aceitaria participar de qualquer roubada só pela fama de 15 minutos?' },
  { id: 'p-e-20', rarity: 'especial', category: 'amizade', text: 'Quem provavelmente deixaria um amigo pagar o mico sozinho só pra rir de longe?' },
  { id: 'p-e-21', rarity: 'especial', category: 'dinheiro', text: 'Quem provavelmente vendaria os próprios princípios por uma quantia boa o suficiente?' },
  { id: 'p-e-22', rarity: 'especial', category: 'competicao', text: 'Quem provavelmente sabotaria um colega de time só pra brilhar mais?' },
  { id: 'p-e-23', rarity: 'especial', category: 'escola', text: 'Quem provavelmente colaria numa prova e ainda ajudaria a colar os outros só pra não ficar sozinho na roubada?' },
  { id: 'p-e-24', rarity: 'especial', category: 'situacoes-sociais', text: 'Quem provavelmente ia armar uma cilada só pra ver a reação de alguém?' },
  { id: 'p-e-25', rarity: 'especial', category: 'decisoes-ruins', text: 'Quem provavelmente ia jogar um amigo debaixo do ônibus pra se safar de uma bronca?' },

  // ============================================================
  // CAOS (mudam a rodada de verdade)
  // ============================================================
  {
    id: 'p-x-01',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem está se achando demais porque está ganhando?',
    effect: { type: 'leader_only_vote' },
  },
  {
    id: 'p-x-02',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem faria qualquer coisa por dinheiro?',
    effect: {
      type: 'winner_choice',
      options: [
        { key: 'pontos', label: '+2 pontos', delta: 2 },
        { key: 'imunidade', label: '+1 ponto e imunidade na próxima rodada', delta: 1, immunity: true },
      ],
    },
  },
  {
    id: 'p-x-03',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem tá com aquela cara de "eu mando mais que todo mundo aqui"?',
    effect: { type: 'leader_only_vote' },
  },
  {
    id: 'p-x-04',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem venderia a alma pra não fazer feio na frente de todo mundo?',
    effect: {
      type: 'winner_choice',
      options: [
        { key: 'pontos', label: '+2 pontos', delta: 2 },
        { key: 'imunidade', label: '+1 ponto e imunidade na próxima rodada', delta: 1, immunity: true },
      ],
    },
  },
  {
    id: 'p-x-05',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem provavelmente vira o alvo número 1 quando o grupo decide implicar com alguém?',
    effect: { type: 'leader_only_vote' },
  },
  {
    id: 'p-x-06',
    rarity: 'caos',
    category: 'caos',
    text: 'Quem topa fazer qualquer aposta idiota só pra não parecer covarde?',
    effect: {
      type: 'winner_choice',
      options: [
        { key: 'pontos', label: '+2 pontos', delta: 2 },
        { key: 'imunidade', label: '+1 ponto e imunidade na próxima rodada', delta: 1, immunity: true },
      ],
    },
  },

  // ============================================================
  // LENDÁRIA (raras, memoráveis)
  // ============================================================
  {
    id: 'p-l-01',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem mais provavelmente faria uma merda monumental?',
    effect: { type: 'double_points_no_tie' },
  },
  {
    id: 'p-l-02',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem é o mais sortudo do grupo?',
    effect: { type: 'random_bonus', values: [3, 2, 1, -1] },
  },
  {
    id: 'p-l-03',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem você escolheria para carregar a culpa por algo que você fez?',
    effect: { type: 'winner_curse' },
  },
  {
    id: 'p-l-04',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem provavelmente ia incendiar o grupo inteiro numa única mensagem de madrugada?',
    effect: { type: 'double_points_no_tie' },
  },
  {
    id: 'p-l-05',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem é a pessoa mais imprevisível da mesa agora?',
    effect: { type: 'random_bonus', values: [3, 2, 1, -1] },
  },
  {
    id: 'p-l-06',
    rarity: 'lendaria',
    category: 'lendaria',
    text: 'Quem você mandaria resolver um problema seu sabendo que pode piorar tudo?',
    effect: { type: 'winner_curse' },
  },
];

module.exports = PACK_PADRAO;
